name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2  # Updated to use a specific version
        id: snake-gif
        with:
          github_user_name: joesef1  # Replace with your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
      - run: git status
      - name: Push changes
        uses: github-actions-x/commit@v2.9  # Updated to use a maintained action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
